Repository graphql/graphql-spec, pull requests merged in 2018-10, with the labels that each got.

#514 Fix grammar
  spec/Section 2 -- Language.md
  spec/Section 3 -- Type System.md
Labels: CLA Signed, clarification

#506 Correct description of directive example
  spec/Section 3 -- Type System.md
Labels: CLA Signed, clarification

#504 Change scheme for URLs from http to https where https is available.
  README.md
  spec/GraphQL.md
  spec/Section 2 -- Language.md
  spec/Section 3 -- Type System.md
  spec/Section 4 -- Introspection.md
Labels: CLA Signed, clarification

#493 Editorial changes on the spec document.
  spec/Section 3 -- Type System.md
Labels: CLA Signed, clarification

#510 [RFC] Allow directives on variable definitions
  spec/Appendix B -- Grammar Summary.md
  spec/Section 2 -- Language.md
  spec/Section 3 -- Type System.md
Labels: CLA Signed, RFC

#480 Add example of negative integer coercion to ID
  spec/Section 3 -- Type System.md
Labels: CLA Signed, 🤷‍♀️ Spec Ambiguity

#519 Revamp Contributing and add GH templates
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: CLA Signed, 🐝 Process
