Repository graphql/graphql-spec, pull requests merged in 2019-07, with the labels that each got.

#574 Add missing '&' to Punctuator production (graphql#573)
  spec/Appendix B -- Grammar Summary.md
  spec/Section 2 -- Language.md
Labels: ✏️ Editorial

#520 Fix ambiguity about optional variables in non-null args
  spec/Section 5 -- Validation.md
Labels: CLA Signed, ✏️ Editorial, 🤷‍♀️ Spec Ambiguity

#536 Introspection: Clarify nullability of fields in `__Type` type
  spec/Section 4 -- Introspection.md
Labels: CLA Signed, ✏️ Editorial

#546 Fix grammar in Section 3 -- Type System.md
  spec/Section 3 -- Type System.md
Labels: CLA Signed, ✏️ Editorial

#537 [Fix] Typos
  CONTRIBUTING.md
Labels: CLA Signed, 🐝 Process

#524 Update spec/Section 4 -- Introspection.md
  spec/Section 4 -- Introspection.md
Labels: CLA Signed, ✏️ Editorial

#538 Synchronise grammar rules across the spec
  spec/Appendix B -- Grammar Summary.md
  spec/Section 3 -- Type System.md
Labels: CLA Signed, ✏️ Editorial

#535 Remove contradictory language
  spec/Section 3 -- Type System.md
Labels: CLA Signed, ✏️ Editorial

#593 Editorial: Make grammar recursion more clear
  spec/Appendix A -- Notation Conventions.md
  spec/Appendix B -- Grammar Summary.md
  spec/Section 3 -- Type System.md
Labels: ✏️ Editorial
