Repository graphql/graphql-spec, pull requests merged in 2020-01, with the labels that each got.

#667 [RFC Sketch] Defer and Stream Directives
  rfcs/DeferStream.md
Labels: 💭 Strawman (RFC 0)

#657 [RFC] Add note recommending directive names to be namespaced
  spec/Section 2 -- Language.md
  spec/Section 3 -- Type System.md
Labels: ✏️ Editorial

#658 Added missing parameter in call to CollectFields()
  spec/Section 6 -- Execution.md
Labels: 🤷‍♀️ Ambiguity

#599 Clarify that lexing is greedy
  spec/Appendix A -- Notation Conventions.md
  spec/Appendix B -- Grammar Summary.md
  spec/Section 2 -- Language.md
Labels: 🏁 Accepted (RFC 3), 🤷‍♀️ Ambiguity

#601 RFC: Number value literal lookahead restrictions
  spec/Appendix B -- Grammar Summary.md
  spec/Section 2 -- Language.md
Labels: 🏁 Accepted (RFC 3)

#659 Fixed that `CoerceArgumentValues` incorrectly refers to `variableType`
  spec/Section 6 -- Execution.md
Labels: ✏️ Editorial

#597 Improve clarity of scalar types
  spec/Section 3 -- Type System.md
Labels: ✏️ Editorial

#472 [RFC] Repeatable directives
  spec/Appendix B -- Grammar Summary.md
  spec/Section 3 -- Type System.md
  spec/Section 4 -- Introspection.md
  spec/Section 5 -- Validation.md
Labels: 🏁 Accepted (RFC 3)

#669 [editorial] Localized note about order of skip and include directives
  spec/Section 6 -- Execution.md
Labels: ✏️ Editorial

#671 [editorial] Fix formatting of algorithms in Validation section
  spec/Section 5 -- Validation.md
Labels: ✏️ Editorial

#373 RFC: Allow interfaces to implement other interfaces
  spec/Section 3 -- Type System.md
  spec/Section 4 -- Introspection.md
  spec/Section 5 -- Validation.md
Labels: 🏁 Accepted (RFC 3)
