Repository graphql/graphql-spec, pull requests merged in 2021-04, with the labels that each got.

#828 Add definition of selectionSet to CreateSourceEventStream
  spec/Section 6 -- Execution.md
Labels: ✏️ Editorial

#726 Formatting: use markdown lists in 'one of' lists
  spec/Appendix B -- Grammar Summary.md
  spec/Section 2 -- Language.md
  spec/Section 3 -- Type System.md
Labels: 🐝 Process

#774 Add FAQ about @defer on fragments vs fields
  rfcs/DeferStream.md
Labels: 📣 RFC document

#748 Clarify how lexical tokens are separated
  spec/Section 2 -- Language.md
Labels: ✏️ Editorial

#835 Rename references from master to main
  .travis.yml
  CONTRIBUTING.md
  README.md
  rfcs/InputUnion.md
  spec/GraphQL.md
  spec/Section 3 -- Type System.md
Labels: ✏️ Editorial

#692 Add discussion on client re-renders, batched responses
  rfcs/DeferStream.md
Labels: 📣 RFC document

#780 Clarify that Float does not include NaN or infinity
  spec/Section 3 -- Type System.md
  spec/Section 6 -- Execution.md
Labels: ✏️ Editorial

#803 Replace 'query error' with 'request error'
  spec/Section 3 -- Type System.md
  spec/Section 5 -- Validation.md
  spec/Section 6 -- Execution.md
  spec/Section 7 -- Response.md
Labels: 🏁 Accepted (RFC 3)

#838 Editorial: clarify input object introspection
  spec/Section 4 -- Introspection.md
Labels: ✏️ Editorial

#842 Editorial: root types
  spec/Section 3 -- Type System.md
Labels: ✏️ Editorial

#841 Editorial: Query shorthand
  spec/Section 2 -- Language.md
Labels: ✏️ Editorial

#839 Editorial: Refine design principles
  spec/Section 1 -- Overview.md
Labels: ✏️ Editorial

#843 Editorial: Clarify field aliases
  spec/Section 2 -- Language.md
Labels: ✏️ Editorial

#765 Update 'Field Collection' explanation
  spec/Section 6 -- Execution.md
Labels: ✏️ Editorial

#598 Avoid parse ambiguity on types & extensions
  spec/Appendix B -- Grammar Summary.md
  spec/Section 3 -- Type System.md
Labels: 🏁 Accepted (RFC 3), 🤷‍♀️ Ambiguity

#775 __Type represents all types in the system
  spec/Section 4 -- Introspection.md
Labels: ✏️ Editorial

#846 RFC: Adding a glossary to the GraphQL Specification
  rfcs/glossary/Appendix C -- Glossary.md
  rfcs/glossary/README.md
Labels: 📣 RFC document

#840 Editorial: Clarify document grammar rules
  spec/Appendix B -- Grammar Summary.md
  spec/Section 2 -- Language.md
  spec/Section 3 -- Type System.md
  spec/Section 5 -- Validation.md
Labels: ✏️ Editorial

#844 Editorial: Clarify meta-fields in introspection
  spec/Section 4 -- Introspection.md
Labels: ✏️ Editorial

#777 Spec edits to reduce "query ambiguity"
  CONTRIBUTING.md
  README.md
  spec/Section 1 -- Overview.md
  spec/Section 2 -- Language.md
  spec/Section 3 -- Type System.md
  spec/Section 4 -- Introspection.md
  spec/Section 5 -- Validation.md
  spec/Section 6 -- Execution.md
  spec/Section 7 -- Response.md
Labels: ✏️ Editorial

#649 [RFC] Custom Scalar Specification URLs
  spec/Section 3 -- Type System.md
  spec/Section 4 -- Introspection.md
Labels: 🏁 Accepted (RFC 3)

#816 State that built-in mandatory directives must be omitted
  spec/Section 3 -- Type System.md
Labels: ✏️ Editorial

#847 Clarity in Section 3
  spec/Section 3 -- Type System.md
Labels: ✏️ Editorial

#686 make clear that some String escape sequences are optional
  spec/Section 2 -- Language.md
Labels: ✏️ Editorial

#850 Upgrade to spec-md@3
  package-lock.json
  package.json
  publish.sh
Labels: 🐝 Process

#851 Fix: Syntax highlighting in example
  spec/Section 3 -- Type System.md
Labels: ✏️ Editorial

#852 Update to spec-md@3.0.2
  package-lock.json
  package.json
Labels: 🐝 Process

#776 RFC: __typename is not valid at subscription root
  spec/Section 4 -- Introspection.md
  spec/Section 5 -- Validation.md
Labels: 🏁 Accepted (RFC 3)

#684 clarify that utf-8 is just a possible encoding of strings
  spec/Section 3 -- Type System.md
Labels: ✏️ Editorial, 🤷‍♀️ Ambiguity

#848 fixed introspection field "specifiedBy" to "specifiedByURL"
  spec/Section 3 -- Type System.md
  spec/Section 4 -- Introspection.md
Labels: 🤷‍♀️ Ambiguity

#856 Editorial: Define 'Schema Specification URL'
  spec/Section 3 -- Type System.md
  spec/Section 4 -- Introspection.md
Labels: ✏️ Editorial

#858 Add spellcheck to test suite
  README.md
  cspell.yml
  package-lock.json
  package.json
  spec/Appendix A -- Notation Conventions.md
  spec/Section 2 -- Language.md
  spec/Section 5 -- Validation.md
  spec/Section 7 -- Response.md
Labels: ✏️ Editorial, 🐝 Process
