Repository graphql/graphql-spec, pull requests merged in 2021-01, with the labels that each got.

#746 RFC: Schema Coordinates
  rfcs/SchemaCoordinates.md
Labels: 📣 RFC document

#812 Update dependencies
  .travis.yml
  package-lock.json
  package.json
  yarn.lock
Labels: 🐝 Process

#811 Editorial: s/server/service
  spec/Section 1 -- Overview.md
  spec/Section 2 -- Language.md
  spec/Section 3 -- Type System.md
  spec/Section 4 -- Introspection.md
  spec/Section 5 -- Validation.md
  spec/Section 6 -- Execution.md
  spec/Section 7 -- Response.md
Labels: ✏️ Editorial

#701 Disallow non-breakable chains of circular references in Input Objects
  spec/Section 3 -- Type System.md
Labels: 🏁 Accepted (RFC 3)

#813 Editorial: Clean trailing whitespace
  spec/Section 3 -- Type System.md
Labels: ✏️ Editorial
