Repository graphql/graphql-spec, pull requests merged in 2022-06, with the labels that each got.

#916 Rename VariableDefinitions to VariablesDefinition
  spec/Appendix B -- Grammar Summary.md
  spec/Section 2 -- Language.md
  spec/Section 6 -- Execution.md
Labels: ✏️ Editorial

#925 consistent indentation and punctuation
  spec/Section 5 -- Validation.md
Labels: ✏️ Editorial

#849 RFC: Allow full unicode range
  build.sh
  package.json
  spec/Appendix B -- Grammar Summary.md
  spec/Section 2 -- Language.md
  spec/metadata.json
Labels: 🏁 Accepted (RFC 3)

#949 Define request, note it is transport independent
  spec/Section 1 -- Overview.md
  spec/Section 2 -- Language.md
  spec/Section 6 -- Execution.md
  spec/Section 7 -- Response.md
Labels: ✏️ Editorial

#927 use `findDog` query from example schema only after defining it
  spec/Section 5 -- Validation.md
Labels: ✏️ Editorial

#805 Allow deprecation of input values (field args, directive args, input fields)
  spec/Section 3 -- Type System.md
  spec/Section 4 -- Introspection.md
Labels: 🏁 Accepted (RFC 3)

#873 Clarify query shorthand relationship with directives
  spec/Section 2 -- Language.md
Labels: ✏️ Editorial

#961 Fix scripts to enable running on Windows
  package.json
Labels: 🐝 Process

#959 Light editorial around delivery agnostic subscriptions
  spec/Section 6 -- Execution.md
Labels: ✏️ Editorial

#958 Leaf field selections clarification
  spec/Section 5 -- Validation.md
Labels: ✏️ Editorial
