Repository graphql/graphql-spec, pull requests merged in 2023-02, with the labels that each got.

#891 Add explanation about argument name uniqueness.
  spec/Section 3 -- Type System.md
Labels: 🏁 Accepted (RFC 3)

#987 Fix ambiguity around when schema definition may be omitted
  spec/Section 3 -- Type System.md
Labels: 🏁 Accepted (RFC 3), ✏️ Editorial

#1009 Add links to contributed custom scalar specs at scalars.graphql.org
  spec/Section 3 -- Type System.md
Labels: ✏️ Editorial
