Repository graphql/graphql-spec, pull requests merged in 2025-06, with the labels that each got.

#1168 Add 'Assert' consistency to algorithm format check
  .github/algorithm-format-check.mjs
  spec/Section 2 -- Language.md
  spec/Section 6 -- Execution.md
Labels: ✏️ Editorial

#860 [RFC] Prevent @skip and @include on root subscription selection set
  spec/Section 5 -- Validation.md
Labels: 🏁 Accepted (RFC 3)

#1159 Define "execution result" and "request error result"
  spec/Section 6 -- Execution.md
  spec/Section 7 -- Response.md
Labels: 🚀 Next Stage?, ✏️ Editorial
