Repository graphql/graphql-spec, pull requests merged in 2025-07, with the labels that each got.

#1102 Define Data Collections used in the spec
  spec/Appendix A -- Notation Conventions.md
  spec/GraphQL.md
Labels: 🏁 Accepted (RFC 3)

#1096 Fixed unclear wording in the validation section
  spec/Section 5 -- Validation.md
Labels: ✏️ Editorial

#1170 Add descriptions to executable documents | 2025 Update
  spec/Appendix B -- Grammar Summary.md
  spec/Section 1 -- Overview.md
  spec/Section 2 -- Language.md
  spec/Section 3 -- Type System.md
  spec/Section 6 -- Execution.md
Labels: 🏁 Accepted (RFC 3)

#1175 Minor editorial tweaks following the merge of #1039
  spec/Section 3 -- Type System.md
  spec/Section 5 -- Validation.md
  spec/Section 6 -- Execution.md
Labels: 🚀 Next Stage?, ✏️ Editorial

#1176 Fix typo in merged "executable documents" PR
  spec/Section 3 -- Type System.md
Labels: 🚀 Next Stage?, ✏️ Editorial
